version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: codenames-db
    environment:
      POSTGRES_DB: codenames_dev
      POSTGRES_USER: codenames_user
      POSTGRES_PASSWORD: codenames_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - codenames-network

  redis:
    image: redis:7-alpine
    container_name: codenames-redis
    ports:
      - "6379:6379"
    networks:
      - codenames-network

volumes:
  postgres_data:

networks:
  codenames-network:
    driver: bridge
